--Q1. WHAT IS SQL ?
--A.SQL IS A STRUCTURED QUERY LANGUAGE THAT IS USED
--TO STORE,MANAGE,RETRIEVE,AND MANIPULATE DATA IN RELATIONAL DATABASE.

--Q2. WHAT ARE DIFFERENT TYPES OF SQL COMMANDS ?
--A.SQL IS DIVIDED TO 4 MAIN CATEGORIES EACH CATEGORY IMPLEMENT 
--SPECIFIC COMMANDS.
--1.DML:
--a)INSERT
--b)UPDATE
--c)Delete
--2.DDL:
--a)CREATE
--b)ALTER
--c)DROP
--3.DCL:
--a)DENY
--b)GRANT
--4.DQL:
--a)SELECT

--Q3.WHAT IS A PRIMARY KEY ?
--A.PRIMARY KEY IS AN IDENTIFIER FOR EACH TABLE AND IT MAKES EACH
--RECORD IN THE TABLE UNIQUE,AND EVERY PRIMARY KEY CAN HELP US 
--IN CREATING RELATIONAL TABLE AND JOING TABLES TOGETHER.

--Q4.WHAT IS FOREIGN KEY ?
--A.A FOREIGN KEY IS A KEY USED TO RELATE EACH TABLE WITH ONE ANOTHER,
--AND EVERY FOREIGN KEY IS BASICALLY GENERATED FROM A PRIMARY KEY IN A 
--SPECIFIC TABLE.

--Q5.WHAT IS COMPOSITE KEY ?
--A.A COMPOSITE KEY,TWO OR MORE PRIMARY KEYS COMBINED TOGETHER IN ONE TABLE,
--IT IS MAINLY USED IN MANY TO MANY RELATIONAL DATA AND USED TO NORMALIZE DATA ,
--IT HELPS SIMPLIFY DATA IN MULTIPLE TABLES AND MAKES RETRIEVING DATA EASIER.

--Q6.WHAT IS DATABASE ?
--A.DATABASE IS AN ORGANISED DATA,AND IS USED TO STORE MASSIVE AMOUNT OF DATA AND GIVES US THE ABILITY TO 
--CERTAIN USERS TO RETRIEVE,UPDATE,DELETE,MODIFY,READ THE DATA.

--Q7.WHAT IS CONSTRAINTS ?
--CONSTRAINTS IN MY OWN UNDERSTANDING ARE LIMITATION THAT SQL PROVIDE,TO MANAGE DATA AND MAKE IT
--MORE FLEXIBLE,BUT ACCURATE ON THE OTHER HAND.

--Q8.GROUP BY VS ORDER BY :
--GROUP BY IS A ONE VALUE AGGREGATE FUNCTION,USED TO MANAGE DATA AND CETEGORIZE THE DATA IN A WAY 
--THAT THE USER SPECIFIES IT.
--ORDER BY IS A FUNCTION THAT ALLOW THE USER SORT THE COLUMNS IN ASCENDING OR EVEN DESCENDING WAY.

--Q9.DESCRIBE THE DIFFERENCE BETWEEN HAVING AND WHERE CLAUSE IN SQL ?
--HAVING IS A CLAUSE ONLY USED WITH GROUP BY TO ADD CONDTION TO THE STATEMENT.
--WHERE IS A CLAUSE USED IN MOST OF SQL STATEMENTS TO ADD A CONDITION.
--Q10.WHAT IS STORED PROCEDURES?
--IT IS A LIST OF PROCEDURES STORED IN SQL,AND IT MAKES APPLYING CERTAIN OPERATIONS ON THE TABLES
--HANDY AND EASY ONLY BY SELECTING AND CALLING THE PROCEDURE NAME STORED IN THE DATABASE.

--Q11.WHAT ARE AGGREGATE FUNCTIONS?
--AGGREGATE FUNCTIONS ARE SQL STORED FUNCTIONS USED FOR CALCULATIONS THAT RETURN ONE VALUE,FOR AN EXAMPLE: SUM,AVG,COUNT,MIN,MAX.

--EXPLAIN DIFFERENT TYPES OF JOINS WITH EXAMPLE:
--JOIN IS A FUNCTION USED TO JOIN TWO TABLE OR MORE IN ORDER TO BE ABLE TO VIEW 
--AND SELECT MULTIPLE TABLE AND BE ABLE TO APPLY DIFFERENT OPERATIONS ON IT.
--WE HAVE DIFFERENT TYPE OF JOINING
--INNER JOIN EX:
--SELECT *
--FROM TableName tn (ALIAS) JOIN TableName2 tn2 (ALIAS) on tn.Id = tn2.Id
--RIGHT OUTER JOIN EX:
--SELECT *
--FROM TableName tn (ALIAS) RIGHT OUTER JOIN TableName2 tn2 (ALIAS) on tn.Id = tn2.Id
--LEFT OUTER JOIN EX: 
--SELECT *
--FROM TableName tn (ALIAS) LEFT OUTER JOIN TableName2 tn2 (ALIAS) on tn.Id = tn2.Id